// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/birddigital/eth-validator-monitor/pkg/types"
)

type AddValidatorInput struct {
	Pubkey *string `json:"pubkey,omitempty"`
	Index  *int    `json:"index,omitempty"`
	Name   *string `json:"name,omitempty"`
}

type AuthPayload struct {
	// Access token for API authentication
	AccessToken string `json:"accessToken"`
	// Refresh token for obtaining new access tokens
	RefreshToken string `json:"refreshToken"`
	// User information
	User *User `json:"user"`
	// Token expiration time (Unix timestamp)
	ExpiresAt int `json:"expiresAt"`
}

type Balance struct {
	Current      types.BigInt `json:"current"`
	Effective    types.BigInt `json:"effective"`
	Withdrawable types.BigInt `json:"withdrawable"`
}

type HistoricalSnapshot struct {
	Epoch              int          `json:"epoch"`
	Slot               int          `json:"slot"`
	Timestamp          types.Time   `json:"timestamp"`
	Balance            types.BigInt `json:"balance"`
	EffectiveBalance   types.BigInt `json:"effectiveBalance"`
	AttestationSuccess *bool        `json:"attestationSuccess,omitempty"`
	InclusionDelay     *int         `json:"inclusionDelay,omitempty"`
	ProposalSuccess    *bool        `json:"proposalSuccess,omitempty"`
	PerformanceScore   *float64     `json:"performanceScore,omitempty"`
	NetworkPercentile  *float64     `json:"networkPercentile,omitempty"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Performance struct {
	UptimePercentage  float64         `json:"uptimePercentage"`
	ConsecutiveMisses int             `json:"consecutiveMisses"`
	TotalMissed       int             `json:"totalMissed"`
	AttestationScore  float64         `json:"attestationScore"`
	ProposalSuccess   int             `json:"proposalSuccess"`
	ProposalMissed    int             `json:"proposalMissed"`
	Effectiveness     float64         `json:"effectiveness"`
	NetworkAverage    float64         `json:"networkAverage"`
	NetworkPercentile float64         `json:"networkPercentile"`
	SlashingRisk      types.RiskLevel `json:"slashingRisk"`
	InactivityScore   int             `json:"inactivityScore"`
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Rewards struct {
	Expected      types.BigInt `json:"expected"`
	Actual        types.BigInt `json:"actual"`
	Effectiveness float64      `json:"effectiveness"`
}

type Subscription struct {
}

type User struct {
	ID        string      `json:"id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	Roles     []string    `json:"roles"`
	CreatedAt types.Time  `json:"createdAt"`
	LastLogin *types.Time `json:"lastLogin,omitempty"`
}
