// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/birddigital/eth-validator-monitor/internal/database/models"
	"github.com/birddigital/eth-validator-monitor/pkg/types"
)

type AlertConnection struct {
	// List of alerts
	Edges []*AlertEdge `json:"edges"`
	// Pagination info
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of items
	TotalCount int `json:"totalCount"`
}

type AlertEdge struct {
	// Cursor for this item
	Cursor string `json:"cursor"`
	// Alert node
	Node *models.Alert `json:"node"`
}

type AlertFilterInput struct {
	// Filter by validator index
	ValidatorIndex *int `json:"validatorIndex,omitempty"`
	// Filter by alert type
	Type *types.AlertType `json:"type,omitempty"`
	// Filter by severity
	Severity *types.AlertSeverity `json:"severity,omitempty"`
	// Filter by resolved status
	Resolved *bool `json:"resolved,omitempty"`
	// Filter by time range
	CreatedFrom *types.Time `json:"createdFrom,omitempty"`
	CreatedTo   *types.Time `json:"createdTo,omitempty"`
}

type AlertSortInput struct {
	Field     AlertSortField `json:"field"`
	Direction *SortDirection `json:"direction,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	// Whether there are more items
	HasNextPage bool `json:"hasNextPage"`
	// Whether there are previous items
	HasPreviousPage bool `json:"hasPreviousPage"`
	// Cursor to the start of the page
	StartCursor *string `json:"startCursor,omitempty"`
	// Cursor to the end of the page
	EndCursor *string `json:"endCursor,omitempty"`
}

type PaginationInput struct {
	// Number of items per page (max 100)
	Limit *int `json:"limit,omitempty"`
	// Cursor for pagination
	Cursor *string `json:"cursor,omitempty"`
}

type Query struct {
}

type SnapshotConnection struct {
	// List of snapshots
	Edges []*SnapshotEdge `json:"edges"`
	// Pagination info
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of items
	TotalCount int `json:"totalCount"`
}

type SnapshotEdge struct {
	// Cursor for this item
	Cursor string `json:"cursor"`
	// Snapshot node
	Node *models.ValidatorSnapshot `json:"node"`
}

type SnapshotFilterInput struct {
	// Filter by validator index
	ValidatorIndex *int `json:"validatorIndex,omitempty"`
	// Filter by time range
	TimeFrom *types.Time `json:"timeFrom,omitempty"`
	TimeTo   *types.Time `json:"timeTo,omitempty"`
	// Filter by epoch range
	EpochFrom *int `json:"epochFrom,omitempty"`
	EpochTo   *int `json:"epochTo,omitempty"`
	// Filter by minimum effectiveness score
	MinEffectiveness *float64 `json:"minEffectiveness,omitempty"`
	// Only include online validators
	OnlineOnly *bool `json:"onlineOnly,omitempty"`
}

type SnapshotSortInput struct {
	Field     SnapshotSortField `json:"field"`
	Direction *SortDirection    `json:"direction,omitempty"`
}

type Subscription struct {
}

type ValidatorConnection struct {
	// List of validators
	Edges []*ValidatorEdge `json:"edges"`
	// Pagination info
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of items
	TotalCount int `json:"totalCount"`
}

type ValidatorEdge struct {
	// Cursor for this item
	Cursor string `json:"cursor"`
	// Validator node
	Node *models.Validator `json:"node"`
}

type ValidatorFilterInput struct {
	// Filter by validator indices
	Indices []int `json:"indices,omitempty"`
	// Filter by public keys
	Pubkeys []string `json:"pubkeys,omitempty"`
	// Filter by status
	Status *types.ValidatorStatus `json:"status,omitempty"`
	// Filter by monitored flag
	Monitored *bool `json:"monitored,omitempty"`
	// Filter by minimum balance (in Gwei)
	MinBalance *types.BigInt `json:"minBalance,omitempty"`
	// Filter by maximum balance (in Gwei)
	MaxBalance *types.BigInt `json:"maxBalance,omitempty"`
	// Filter by activation epoch range
	ActivationEpochFrom *int `json:"activationEpochFrom,omitempty"`
	ActivationEpochTo   *int `json:"activationEpochTo,omitempty"`
}

type ValidatorSortInput struct {
	Field     ValidatorSortField `json:"field"`
	Direction *SortDirection     `json:"direction,omitempty"`
}

type AlertSortField string

const (
	AlertSortFieldCreatedAt AlertSortField = "CREATED_AT"
	AlertSortFieldSeverity  AlertSortField = "SEVERITY"
	AlertSortFieldType      AlertSortField = "TYPE"
)

var AllAlertSortField = []AlertSortField{
	AlertSortFieldCreatedAt,
	AlertSortFieldSeverity,
	AlertSortFieldType,
}

func (e AlertSortField) IsValid() bool {
	switch e {
	case AlertSortFieldCreatedAt, AlertSortFieldSeverity, AlertSortFieldType:
		return true
	}
	return false
}

func (e AlertSortField) String() string {
	return string(e)
}

func (e *AlertSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertSortField", str)
	}
	return nil
}

func (e AlertSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SnapshotSortField string

const (
	SnapshotSortFieldTime           SnapshotSortField = "TIME"
	SnapshotSortFieldValidatorIndex SnapshotSortField = "VALIDATOR_INDEX"
	SnapshotSortFieldBalance        SnapshotSortField = "BALANCE"
	SnapshotSortFieldEffectiveness  SnapshotSortField = "EFFECTIVENESS"
)

var AllSnapshotSortField = []SnapshotSortField{
	SnapshotSortFieldTime,
	SnapshotSortFieldValidatorIndex,
	SnapshotSortFieldBalance,
	SnapshotSortFieldEffectiveness,
}

func (e SnapshotSortField) IsValid() bool {
	switch e {
	case SnapshotSortFieldTime, SnapshotSortFieldValidatorIndex, SnapshotSortFieldBalance, SnapshotSortFieldEffectiveness:
		return true
	}
	return false
}

func (e SnapshotSortField) String() string {
	return string(e)
}

func (e *SnapshotSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SnapshotSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SnapshotSortField", str)
	}
	return nil
}

func (e SnapshotSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SnapshotSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SnapshotSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ValidatorSortField string

const (
	ValidatorSortFieldIndex            ValidatorSortField = "INDEX"
	ValidatorSortFieldPubkey           ValidatorSortField = "PUBKEY"
	ValidatorSortFieldBalance          ValidatorSortField = "BALANCE"
	ValidatorSortFieldEffectiveBalance ValidatorSortField = "EFFECTIVE_BALANCE"
	ValidatorSortFieldStatus           ValidatorSortField = "STATUS"
	ValidatorSortFieldActivationEpoch  ValidatorSortField = "ACTIVATION_EPOCH"
)

var AllValidatorSortField = []ValidatorSortField{
	ValidatorSortFieldIndex,
	ValidatorSortFieldPubkey,
	ValidatorSortFieldBalance,
	ValidatorSortFieldEffectiveBalance,
	ValidatorSortFieldStatus,
	ValidatorSortFieldActivationEpoch,
}

func (e ValidatorSortField) IsValid() bool {
	switch e {
	case ValidatorSortFieldIndex, ValidatorSortFieldPubkey, ValidatorSortFieldBalance, ValidatorSortFieldEffectiveBalance, ValidatorSortFieldStatus, ValidatorSortFieldActivationEpoch:
		return true
	}
	return false
}

func (e ValidatorSortField) String() string {
	return string(e)
}

func (e *ValidatorSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ValidatorSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ValidatorSortField", str)
	}
	return nil
}

func (e ValidatorSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ValidatorSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ValidatorSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
